// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqFdz1V9yKkrS53v3OCvkrjnNEDSDOw7o',
    appId: '1:834609933376:web:81651a36fc3086e03a03a5',
    messagingSenderId: '834609933376',
    projectId: 'memorydirective',
    authDomain: 'memorydirective.firebaseapp.com',
    storageBucket: 'memorydirective.appspot.com',
    measurementId: 'G-Y9KQEJCY9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3NMUpvOCfyrye0W1aI5vHcvXeoDcQMY',
    appId: '1:834609933376:android:501d58d4ed4d64393a03a5',
    messagingSenderId: '834609933376',
    projectId: 'memorydirective',
    storageBucket: 'memorydirective.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtwEGL8gLFRgsUQszKtuB-x9p_2l0wNk',
    appId: '1:834609933376:ios:ccd561084062581c3a03a5',
    messagingSenderId: '834609933376',
    projectId: 'memorydirective',
    storageBucket: 'memorydirective.appspot.com',
    iosClientId: '834609933376-5btmp0ll3lmtetar5kduik0t35nhi6l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.memorydirective',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtwEGL8gLFRgsUQszKtuB-x9p_2l0wNk',
    appId: '1:834609933376:ios:4041551d81020c8e3a03a5',
    messagingSenderId: '834609933376',
    projectId: 'memorydirective',
    storageBucket: 'memorydirective.appspot.com',
    iosClientId: '834609933376-7nj0jpfjk8ab4auqa3e0b89686pu9j3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.memorydirective.RunnerTests',
  );
}
